name: Validate News
description: 'Validate news in the json resources based on new pull request'
inputs:
  pull-request-id:
	description: 'The number of the pull request'
	required: true  
  pull-request-branch:
	description: 'Open pull request url'
	required: true
  secret-token:
	description: 'Github secret token'
	required: true
  ai-secret-token:
	description: 'AI secret token'
	required: true 
runs:
  using: 'composite'
  steps:
	- name: Enable Required Scripts
	  run: chmod u+r+x .github/workflows/actions/edit-news-pr-action/write-description-text.sh
	  shell: bash
	- name: Check out Branch ${{ inputs.pull-request-branch }}
	  uses: actions/checkout@v2
	  with: