name: 'Add News Action'
description: 'Include news in the json resources based on opened issue'
inputs:
  branch-name:
    description: 'The name of the branch to edit the file on'
    required: true
  issue-number:
    description: 'The number of the issue'
    required: true
  issue-body:
    description: 'The body of the issue'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Prepare Env
      run: |
         chmod u+r+x ./.github/workflows/actions/add-news-action/run-enabler.kts
         git update-index --chmod=+x ./.github/workflows/actions/add-news-action/run-enabler.kts
      shell: bash
    - name: Checkout the branch
      run: git checkout ${{ inputs.branch-name }}
      shell: bash
    - name: Enable scripts
      run: kotlinc -script ./.github/workflows/scripts/news/run-enabler.main.kts
      shell: bash
    - name: Edit file
      run: bash ./.github/workflows/actions/add-news-action/add-news.main.kts "${{ inputs.branch-name }}" ${{ inputs.issue-label }} ${{ inputs.issue-body }}
      shell: bash