name: 'Add News Action'
description: 'Include news in the json resources based on opened issue'
inputs:
  issue-number:
    description: 'The number of the issue'
    required: true
  issue-body:
    description: 'The body of the issue'
    required: true
  issue-title:
    description: 'The title of the issue'
    required: true  
  secret-token:
    description: 'Github secret token'
    required: true  
runs:
  using: 'composite'
  
  steps:
    - name: Enable Action Scripts
      run: |
        chmod u+r+x .github/workflows/actions/add-news-action/run-enabler.main.kts
        kotlinc -script .github/workflows/actions/add-news-action/run-enabler.main.kts
      shell: bash           
    - name: Checkout Repo ${{ inputs.issue-number }}
      uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 0
    - name: Checkout New Branch
      run: |
        git fetch origin
        git checkout -b news/${{ inputs.issue-number }}
        git rebase origin/main
        git commit --allow-empty -m "Start news for issue ${{ inputs.issue-number }}"
        git push origin news/${{ inputs.issue-number }}
      shell: bash  
    - name: Download Kotlin Serialization Plugin
      env:
        PLUGIN_VERSION: 1.9.22
        COMPILER_PLUGIN: kotlin-serialization-compiler-plugin
        COMPILER_GROUP: jetbrains/kotlin
      run: .github/workflows/scripts/dependency-resolver.sh $COMPILER_PLUGIN $PLUGIN_VERSION $COMPILER_GROUP
      shell: bash
    - name: Upload Issue To Json File
      run: |
        jsonString=$(jq -n --arg number "${{ inputs.issue-number }}" --arg title "${{ inputs.issue-title }}" --arg body "${{ inputs.issue-body }}" '{number: $number, title: $title, body: $body}')
        echo "::debug::Using json $jsonString" &&
        kotlinc -script .github/workflows/actions/add-news-action/generate-issue-file.main.kts "\"$jsonString\""
      shell: bash  
    - name: Include Issue(${{ inputs.issue-number }}) data to Json
      env:
        PLUGIN_VERSION: 1.9.22
        PLUGIN_NAME: kotlin-serialization-compiler-plugin
      run: |
        plugin=$(.github/workflows/scripts/get-dependency.sh $PLUGIN_NAME $PLUGIN_VERSION)
        echo "::debug::Using plugin $plugin" &&
        kotlinc -script -Xplugin="$plugin" .github/workflows/actions/add-news-action/add-news.main.kts
      shell: bash
    - name: Commit Changes
      run: |
        git add .
        git commit -m "Add news for issue ${{ inputs.issue-number }}"
      shell: bash  
    - name: Push Changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.secret-token }}
        branch: "news/${{ inputs.issue-number }}"  
    - name: Wait before creating PR
      run: sleep 30 # Waits for 30 seconds
      shell: bash 
    - name: Create pull request
      uses: thomaseizinger/create-pull-request@master
      with:
        GITHUB_TOKEN: ${{ inputs.secret-token }}
        head: ${{ github.ref }}
        base: news/${{ inputs.issue-number }}
        title: "An automatically created PR!"
        