name: 'Add News Action'
description: 'Include news in the json resources based on opened issue'
inputs:
  issue-number:
    description: 'The number of the issue'
    required: true
  issue-body:
    description: 'The body of the issue'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Download Kotlin Serialization Plugin
      env:
        PLUGIN_VERSION: 1.9.22
        COMPILER_PLUGIN: kotlin-serialization-compiler-plugin
        COMPILER_GROUP: jetbrains/kotlin
      run: .github/workflows/scripts/dependency-resolver.sh $COMPILER_PLUGIN $PLUGIN_VERSION $COMPILER_GROUP
      shell: bash
    - name: Edit file
      env:
        PLUGIN_VERSION: 1.9.22
        PLUGIN_NAME: kotlin-serialization-compiler-plugin
      run: |
        plugin=$(.github/workflows/scripts/get-dependency.sh $PLUGIN_NAME $PLUGIN_VERSION)
        echo "Using plugin $plugin" &&
        kotlinc -script -Xplugin="$plugin" .github/workflows/actions/add-news-action/add-news.main.kts "${{ inputs.issue-number }} , ${{ inputs.issue-body }}"
      shell: bash

