name: 'Add News Action'
description: 'Include news in the json resources based on opened issue'
inputs:
  branch-name:
    description: 'The name of the branch to edit the file on'
    required: true
  issue-body:
    description: 'The body of the issue'
    required: true
  issue-number:
    description: 'The number of the issue'
    required: true
runs:
  using: 'composite'
  
  steps:
    - name: Download Kotlin Serialization Plugin
      run: .github/workflows/scripts/dependency-resolver.sh "kotlin-serialization-compiler-plugin 1.9.22 jetbrains/kotlin"
      shell: bash
    - name: Edit file
      run: |
        PLUGIN_VERSION=1.9.22
        COMPILER_PLUGIN=kotlinx-serialization-compiler-plugin.jar
        kotlinc -script -Xplugin=./.github/workflows/.temp/$COMPILER_PLUGIN .github/workflows/actions/add-news-action/add-news.main.kts " resources/news.json , ${{ inputs.issue-number }} , { ${{ inputs.branch-name }} , ${{ inputs.issue-body }} "
      shell: bash