name: 'Add News Action'
description: 'Include news in the json resources based on opened issue'
inputs:
  issue-number:
    description: 'The number of the issue'
    required: true
  issue-body:
    description: 'The body of the issue'
    required: true
  issue-title:
    description: 'The title of the issue'
    required: true  
  secret-token:
    description: 'Github secret token'
    required: true  
runs:
  using: 'composite'
  steps:
    - name: Enable Action Scripts
      run: |
          chmod u+r+x .github/workflows/actions/add-news-action/run-enabler.main.kts
          kotlinc -script .github/workflows/actions/add-news-action/run-enabler.main.kts
      shell: bash           
    - name: Checkout Branch for issue ${{ inputs.issue-number }}
      uses: actions/checkout@v2
      with:
        ref: main
      run: git checkout -b news/${{ inputs.issue-number }}
      shell: bash    
    - name: Download Kotlin Serialization Plugin
      env:
        PLUGIN_VERSION: 1.9.22
        COMPILER_PLUGIN: kotlin-serialization-compiler-plugin
        COMPILER_GROUP: jetbrains/kotlin
      run: .github/workflows/scripts/dependency-resolver.sh $COMPILER_PLUGIN $PLUGIN_VERSION $COMPILER_GROUP
      shell: bash
    - name: Upload Issue To Json File
      run: 'kotlinc -script .github/workflows/actions/add-news-action/generate-issue-file.main.kts "{ number: ${{inputs.issue-number}}, title: \"${{inputs.issue-title}}\", body: \"${{inputs.issue-body}}\" }"'
      shell: bash  
    - name: Include Issue(${{ inputs.issue-number }}) data to Json
      env:
        PLUGIN_VERSION: 1.9.22
        PLUGIN_NAME: kotlin-serialization-compiler-plugin
      run: |
        plugin=$(.github/workflows/scripts/get-dependency.sh $PLUGIN_NAME $PLUGIN_VERSION)
        echo "::debug::Using plugin $plugin" &&
        kotlinc -script -Xplugin="$plugin" .github/workflows/actions/add-news-action/add-news.main.kts
      shell: bash
    - name: "Open Pull request for Issue ${{ inputs.issue-number }}"
      uses: peter-evans/create-pull-request@v6.1.0
      with:
        token: ${{ inputs.secret-token }}
        commit-message: "Add news for issue ${{ inputs.issue-number }}"
        title: "[News] [${{ inputs.issue-number }}] - ${{ inputs.issue-title }}"
        body: "This PR adds news for issue ${{ inputs.issue-number }}."
        branch: news/${{ inputs.issue-number }}
        base: main
        labels: news
        assignees: ${{ github.actor }}
        reviewers: ${{ github.actor }}
        draft: false
        signoff: true
        changes: "This PR adds news for issue ${{ inputs.issue-number }}."