name: 'Add News Action'
description: 'Include news in the json resources based on opened issue'
inputs:
  branch-name:
    description: 'The name of the branch to edit the file on'
    required: true
  issue-number: 
    description: 'The number of the issue'
    required: true  
  issue-body:
    description: 'The body of the issue'
    required: true  
runs:
  using: 'composite'
  steps:
    - name: Allow Scripts
      run: |
        cd .github/workflows/scripts/news
        chmod +x *.sh
        ls -l
        git add *.sh
        echo "News Scripts allowed"
      shell: bash
    - name: Checkout the branch
      run: git checkout ${{ inputs.branch-name }}
      shell: bash
    - name: Edit file
      run: bash ./.github/workflows/scripts/news/add-news.sh ${{ inputs.branch-name }} ${{ inputs.issue-label }} ${{ inputs.issue-body }}
      shell: bash