name: 'Add News Action'
description: 'Include news in the json resources based on opened issue'
inputs:
  branch-name:
    description: 'The name of the branch to edit the file on'
    required: true
  issue-body:
    description: 'The body of the issue'
    required: true
  issue-number:
    description: 'The number of the issue'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Download Kotlin Serialization Plugin
      env:
        PLUGIN_VERSION: 1.9.22
        COMPILER_PLUGIN: kotlinx-serialization-compiler-plugin
        COMPILER_GROUP: jetbrains/kotlin
      run: .github/workflows/scripts/dependency-resolver.sh $COMPILER_PLUGIN $PLUGIN_VERSION $COMPILER_GROUP
      shell: bash
    - name: Edit file
      env:
        PLUGIN_VERSION: 1.9.22
        PLUGIN_NAME: kotlinx-serialization-compiler-plugin
      run: |
      plugin=$(github/workflows/scripts/get-dependency.sh $PLUGIN_NAME $PLUGIN_VERSION)
      kotlinc -script -Xplugin=$plugin .github/workflows/actions/add-news-action/add-news.main.kts " resources/news.json , ${{ inputs.issue-number }} , { ${{ inputs.branch-name }} , ${{ inputs.issue-body }} "
      shell: bash