name: Implement new Issue
on:
    issues:
        types: [opened, labeled]
jobs:
  implement-new-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Setup Git User
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Download kotlin
        uses: fwilhe2/setup-kotlin@main
        with:
          version: 1.9.22
      - name: Setup Enablers
        run: |
          chmod u+r+x .github/workflows/scripts/dependency-resolver.sh
          chmod u+r+x .github/workflows/scripts/get-dependency.sh
      - name: Validate Issue
        if: contains(github.event.issue.labels.*.name, 'news')
        uses: ./.github/workflows/actions/add-news-action/
        with:
          issue-number: ${{ github.event.issue.number }}
          issue-body: ${{ github.event.issue.body }}
          issue-title: ${{ github.event.issue.title }}
          secret-token: ${{ secrets.GITHUB_TOKEN }}