name: New Pull Request
on:
  pull_request:
    types: [opened, labeled]
jobs:
  validate-PR:
    runs-on: ubuntu-latest
    outputs:
      next-job-tag: ${{ steps.validate-issue.outputs.next-job-tag }}
    steps:
      - name: Checking Labels
        id: validate-issue
        run: |
          LABELS_JSON='${{ toJson(github.event.pull_request.labels) }}'
          FIRST_LABEL=$(echo "$LABELS_JSON" | jq -r '.[0].name')
          echo "First label: $FIRST_LABEL"
          echo "::set-output name=next-job-tag::$FIRST_LABEL"
        shell: bash
  include-news-details:
    runs-on: ubuntu-latest
    needs: validate-PR
    if: ${{ needs.validate-PR.outputs.next-job-tag == 'news' }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Setup Git User
      run: |
        git config --global user.name 'news-action[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
    - name: Setup Enablers
      run: |
        chmod u+r+x .github/workflows/scripts/dependency-resolver.sh
        chmod u+r+x .github/workflows/scripts/get-dependency.sh    
    - name: Run News Action
      id: run-news  
      uses: ./.github/workflows/actions/edit-news-pr-action/
      with:
        pull-request-id: ${{ github.event.pull_request.number }}
        pull-request-branch: ${{ github.event.pull_request.head.ref }}
        secret-token: ${{ secrets.GITHUB_TOKEN }}  

                