name: New Pull Request
on:
  pull_request:
    types: [opened, labeled]
jobs:
    check-pull-request:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2  
            - name: Setup Git User
              run: git config --global user.name 'Pull Checker'
            - name: Check Out Branch
              run: |
                 git fetch origin
                 git checkout -b ${{github.event.pull_request.head.ref }}
            - name: Check Label
              run: |       

