name: Implement new Issue
on:
    issues:
        types: [opened, labeled]
jobs:
  createBranch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Setup Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'        
      - name: Create and Push New Branch
        run: |
          NEW_BRANCH="news/${{ github.event.issue.number }}"
          # Check if the branch exists on the remote
          EXISTS=$(git ls-remote --heads origin $NEW_BRANCH)
          if [[ -z "$EXISTS" ]]; then
            echo "Branch $NEW_BRANCH does not exist, creating..."
            git checkout -b $NEW_BRANCH
            git push origin $NEW_BRANCH
          else
            echo "Branch $NEW_BRANCH already exists."
            git checkout -b $NEW_BRANCH

          fi
      - name: Download Kotlin Serialization Plugin
        run: |
          curl -L -o kotlinx-serialization-compiler-plugin.jar https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-serialization/1.5.21/kotlin-serialization-1.5.21.jar
          echo "Downloaded Kotlin Serialization Plugin"
      - name: Run Plugin
        run: |
          kotlinc -script .github/workflows/actions/add-news-action/run-enabler.main.kts
          echo "Ran Plugin"
      - name: Checking issue
        if: contains(github.event.issue.labels.*.name, 'news')
        uses: ./.github/workflows/actions/add-news-action
        with:
          branch-name: ${{ env.NEW_BRANCH }}
          issue-number: ${{ github.event.issue.number }}
          issue-body: ${{ github.event.issue.body }}

      - name: "Opening PR for new issue"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        run: |
          PR_URL=$(gh pr create --base main --head $NEW_BRANCH --title "Add news for issue $ISSUE_NUMBER" --body "This PR adds news for issue $ISSUE_NUMBER" --repo ${{ github.repository }} -w)
          echo "PR created: $PR_URL"
      - name: "Adding PR to issue"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_BODY="This PR adds news for issue #$ISSUE_NUMBER. \n\nCloses #$ISSUE_NUMBER"
          PR_URL=$(gh pr create --base main --head $NEW_BRANCH --title "Add news for issue $ISSUE_NUMBER" --body "$PR_BODY" --repo ${{ github.repository }} -w)
          echo "PR created: $PR_URL"

